### PR TITLE
normalize routes

### PR DESCRIPTION
**Pull request by mcollina**
Closes https://github.com/nearform/titus/issues/642

### CODE REVIEW

**Comment by simoneb** [comment]
This change is not ok because it changes the routes. Without using fp, it will prefix the routes. 

Here's what routes are without this change (only the relevant part is included):

```
└── /
    ├── user (GET)
    │   └── list (GET)
```

And this is what routes are with this change:

```
└── /
    ├── user
    │   ├── list (GET)
    │   └── /user (GET)
```

See that is has prefixed the `/user` route with `user`, making it `/user/user`.

This is something that was mentioned in https://github.com/nearform/titus/issues/642.

Nevertheless, the good thing is that this route is probably unnecessary and in fact never called in the app (it's called in some commented code). Plus, this route implementation is even wrong because it doesn't check if the user is authenticated. If it's not, fastify hangs forever because the route handler is returning undefined:

```
Promise may not be fulfilled with 'undefined' when statusCode is not 204
```

**Comment by mcollina** [comment]
This should be good now. I'm a bit skeptical of the fact that the CI passed.

**Comment by simoneb** [comment]
There are test, as you can see because the build is broken now, but they test the plugin in isolation, hence they don't cover the auto prefixing behavior.

**Comment by mcollina** [comment]
Anyway, this needs to be investigated as it shows a bad practice.

**Comment by skywickenden** [comment]
I've normalised the routes. Including renaming the `health` folder to `healthcheck` 

After discussion with @simoneb  I'm going to include the removal of the `user` route in https://github.com/nearform/titus/pull/594 as it deals with a related issue and will result in conflicts

**Review by simoneb — APPROVED** [review]
LGTM

**Comment by mcollina** [comment]
lgtm, land when you want

**Pull request merged**
