### PR TITLE
replace ecs with eks

### PR DESCRIPTION
**Pull request by ronandoolan2**
In this folder the user can deploy eks instead of ecs

### CODE REVIEW

**Comment by leorossi** [comment]
There are some TF blocks that are commented, can you please remove them?

**Comment by leorossi** [comment]
cc @simoneb

**Comment by simoneb** [comment]
@leorossi before we merge this can we please try this out to confirm everything is working fine?

**Review by simoneb — APPROVED** [review]

**Comment by leorossi** [comment]
tested on our AWS account, and it creates the resource needed for EKS. LGTM.

**Comment by simoneb** [comment]
Perfect, thanks. Let's merge please and close the issue

**Pull request merged**
